FROM alpine
RUN apk add nodejs npm
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

USER appuser
COPY . .
RUN npx tsc
EXPOSE 3000
CMD ["node", "build/index.js"]